server {
    listen 80;
    server_name npdi.cdn.pretendo.cc npdl.cdn.pretendo.cc npfl.c.app.pretendo.cc
    nppl.c.app.pretendo.cc nppl.app.pretendo.cc npts.app.pretendo.cc;
    location = /p01/tasksheet/1//preport {
        default_type application/xml;
        return 200 '<?xml version="1.0" encoding="UTF-8"?><TaskSheet><TitleId>000500001018dc00</TitleId><TaskId>preport</TaskId><ServiceStatus>open</ServiceStatus><Files></Files></TaskSheet>';
    }
    location = /p01/tasksheet/1/preport {
        default_type application/xml;
        return 200 '<?xml version="1.0" encoding="UTF-8"?><TaskSheet><TitleId>000500001018dc00</TitleId><TaskId>preport</TaskId><ServiceStatus>open</ServiceStatus><Files></Files></TaskSheet>';
    }
    location ~ ^/p01/tasksheet/1/[^/]+/CHARA$ {
        default_type application/xml;
        return 200 '<?xml version="1.0" encoding="UTF-8"?><TaskSheet><TitleId>000500001018dc00</TitleId><TaskId>CHARA</TaskId><ServiceStatus>open</ServiceStatus><Files></Files></TaskSheet>';
    }
    location ^~ /super-mario-maker/ {
        proxy_pass http://minio:9000;
        proxy_set_header Host $host;
    }
    location / {
        resolver 8.8.8.8 ipv6=off;
        proxy_ssl_server_name on;
        proxy_set_header Host $host;
        proxy_pass https://$host;
    }
}
